[package]
name = "varuint"
version = "0.3.2"
authors = ["Artem Shein <sc-github@aisys.ru>"]

description = "Variable length signed and unsigned integer types"
repository = "https://github.com/artemshein/varuint"
categories = ["data-structures", "encoding", "compression"]
license = "MIT"
